jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      id: fork
      name: Figure out if running fork PR
      run: '["${{ secrets.DOCKER_REGISTRY_TOKEN }}" == ""] && echo "::set-output name=is_fork_pr::true"
        || echo "::set-output name=is_fork_pr::false"'
    - continue-on-error: true
      env:
        INFLUXDB_VERSION: ${{ matrix.influxdb }}
        MAVEN_JAVA_VERSION: ${{ matrix.jdk }}
      name: Build project
      run: ./compile-and-test.sh
    - continue-on-error: true
      if: matrix.influxdb != '2.3' && matrix.influxdb != '2.4' && matrix.influxdb
        != '2.5'
      name: codecov
      run: 'sudo apt-get update

        sudo apt-get install gpg libdigest-sha-perl -y

        curl -Os https://uploader.codecov.io/latest/linux/codecov

        curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM

        curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig

        curl -s https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring
        --keyring trustedkeys.gpg --import

        gpgv codecov.SHA256SUM.sig codecov.SHA256SUM

        shasum -a 256 -c codecov.SHA256SUM

        chmod +x ./codecov

        ./codecov

        '
    strategy:
      matrix:
        influxdb:
        - '1.1'
        - '1.6'
        - '1.8'
        - '2.3'
        - '2.4'
        - '2.5'
        jdk:
        - 3-openjdk-17-slim
        - 3-jdk-14
        - 3-jdk-8-slim
name: Build from pull request
on:
  repository_dispatch:
    types: trigger-ga___pr.yml
